### ISSUE TITLE
Unable To Start

### ISSUE THREAD

**Issue by RFedz007** [BlackThompson/Painted-Skin#1]
Hi,

I am getting this below mentioned error...

E:\PaintedSkin\Painted-Skin>gradio gradio_UI.py
Traceback (most recent call last):
  File "C:\Users\vkark\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\vkark\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\vkark\AppData\Local\Programs\Python\Python310\Scripts\gradio.exe\__main__.py", line 7, in <module>
  File "C:\Users\vkark\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\cli.py", line 21, in cli
    gradio.reload.main()
  File "C:\Users\vkark\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\reload.py", line 88, in main
    filename, path, watch_dirs, demo_name = _setup_config()
  File "C:\Users\vkark\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\reload.py", line 37, in _setup_config
    app_text = Path(original_path).read_text()
  File "C:\Users\vkark\AppData\Local\Programs\Python\Python310\lib\pathlib.py", line 1135, in read_text
    return f.read()
  File "C:\Users\vkark\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 417: character maps to <undefined>

Kindly help me in fixing this.

Thank You

**Comment by BlackThompson** [comment]
Hi,

It seems you encounter an encoding error.

Could you please run `sys.getdefaultencoding()` and tell me your output?

**Comment by BlackThompson** [comment]
https://blog.csdn.net/weixin_43917485/article/details/108921881
maybe you can follow this link to change your default encoding to utf-8

**Comment by RFedz007** [comment]
Thanks for the help, but I am firstly getting this error when done via pip install requirements

(ERROR: Could not find a version that satisfies the requirement torch==1.13.1+cu116 (from versions: 1.11.0, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 2.0.0, 2.0.1, 2.1.0)
ERROR: No matching distribution found for torch==1.13.1+cu116)

Thank You

**Comment by BlackThompson** [comment]
this is because the cuda version, you need to install `torch`, `torchvision`, `torchaudio` according to your cuda version, and download them from https://pytorch.org/get-started/previous-versions/
